### ISSUE TITLE
新编表情【jerk_off】报错：AttributeError: 'list' object has no attribute 'image'

### ISSUE THREAD

**Issue by LeoWrDeom** [MeetWq/meme-generator-contrib#19]
报错表情：jerk_off
```
08-24 20:16:43 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_memes, lineno=87) failed.
Traceback (most recent call last):
  File "G:\lhcbot\lhcbot\bot.py", line 54, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_memes\__init__.py", line 154, in _
    img = await meme.generate_preview()
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\site-packages\meme_generator\meme.py", line 182, in generate_preview
    return await _generate_preview(default_images, default_texts)
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\site-packages\meme_generator\meme.py", line 177, in _generate_preview
    return await self.__call__(images=images, texts=texts, args=args)
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\site-packages\meme_generator\meme.py", line 144, in __call__
    return await run_sync(cast(Callable[..., BytesIO], self.function))(**values)
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\site-packages\meme_generator\utils.py", line 48, in _wrapper
    result = await loop.run_in_executor(None, pfunc)
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\meme-generator-contrib-main\memes\jerk_off\__init__.py", line 30, in jerk_off
    return make_gif_or_combined_gif(images, maker, 8, 0.1, FrameAlignPolicy.extend_loop)
  File "C:\Users\Leo\AppData\Local\Programs\Python\Python310\lib\site-packages\meme_generator\utils.py", line 229, in make_gif_or_combined_gif
    image = img.image
AttributeError: 'list' object has no attribute 'image'
```

**Comment by dkqdb66** [comment]
更新主仓库，新的gif制作函数现在是传入图片数组的。

**Comment by LeoWrDeom** [comment]
已解决，感谢！
