### ISSUE TITLE
表情fleshlight出现错误，TypeError: 'BuildImage' object is not iterable

### ISSUE THREAD

**Issue by shi-yingyingjiang** [MeetWq/meme-generator-contrib#20]
```python
08-24 21:29:02 [ERROR] nonebot | Running AlconnaMatcher(type='', module=nonebot_plugin_memes.matchers.info, lineno=8) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot_plugin_memes\matchers\info.py", line 63, in _
    img = await run_sync(meme.generate_preview)()
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\utils.py", line 182, in _wrapper
    result = await loop.run_in_executor(None, partial(context.run, pfunc))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\meme_generator\meme.py", line 175, in generate_preview
    return _generate_preview(default_images, default_texts)
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\meme_generator\meme.py", line 170, in _generate_preview
    return self.__call__(images=images, texts=texts, args=args)
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\meme_generator\meme.py", line 154, in __call__
    return self.function(**values)
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\meme_generator\memes\fleshlight\__init__.py", line 59, in fleshlight
    return make_gif_or_combined_gif(
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\meme_generator\utils.py", line 318, in make_gif_or_combined_gif
    images = [img.image for img in imgs]
TypeError: 'BuildImage' object is not iterable
```

**Comment by MeetWq** [comment]
#19

**Comment by shi-yingyingjiang** [comment]
已经更新过了，版本号0.1.2
![屏幕截图 2024-08-24 215549](https://github.com/user-attachments/assets/cbab533a-396e-40aa-9080-d1f6a85c6b15)

**Comment by dkqdb66** [comment]
> 已经更新过了，版本号0.1.2
> ![屏幕截图 2024-08-24 215549](https://github.com/user-attachments/assets/cbab533a-396e-40aa-9080-d1f6a85c6b15)
> 

上面那个是只更新了额外仓库，你这个是只更新了主仓库，你把额外仓库重新克隆过去就行了

**Comment by shi-yingyingjiang** [comment]
还是不行，nb群里有人拉取后可以用了，我的还不行（sad）
